"""Generate a Claude Code starter pack from a scored opportunity.

`opp-os kickoff <opp_id>` writes two files designed for the agent-skills
workflow (/spec -> /plan -> /build):

- PROJECT.md       -- seed brief carrying everything the pipeline learned
- kickoff-prompt.md -- paste into a fresh Claude Code session to start building

Pure templating: no API calls, no key requirements.
"""

from __future__ import annotations

import os
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from opportunity_os.storage import get_opportunity_by_id, get_project_root

GEO_WTP_ANCHORS = {
    "venezuela": "$3-15/mo SaaS ceiling (WTP ~0.25x US); transaction fees beat subscriptions",
    "latam": "$20-50/mo SaaS (WTP ~0.40x US); monthly billing, no annual contracts",
    "colombia": "$20-50/mo SaaS; local payment rails matter (PSE, Nequi)",
    "mexico": "$20-50/mo SaaS; OXXO/SPEI payment options widen the funnel",
    "spain": "$30-80/mo SaaS; EU invoicing and GDPR table stakes",
    "global": "$50-200/mo SaaS; standard card billing",
}


def _slugify(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", (name or "project").lower()).strip("-")
    return slug[:40] or "project"


def _fmt_list(items, limit: int = 5) -> str:
    vals = [str(i).strip() for i in (items or [])[:limit] if str(i).strip()]
    return ", ".join(vals) if vals else "unknown -- validate during /spec"


def _text_or(opp: dict, field: str, fallback: str) -> str:
    """Return the field only if it is a non-empty string.

    Legacy records hold numbers in some text fields (e.g. path_to_first_revenue
    was once a 1-10 score) and None survives .get() defaults -- both must fall
    back, not leak into the brief as 'None' or '6'.
    """
    val = opp.get(field)
    return val.strip() if isinstance(val, str) and val.strip() else fallback


def build_project_md(opp: dict) -> str:
    """Seed PROJECT.md from the opportunity record."""
    name = opp.get("name", "Unknown opportunity")
    geo = (opp.get("geography") or "global").lower()
    wtp_anchor = GEO_WTP_ANCHORS.get(geo, GEO_WTP_ANCHORS["global"])
    score = opp.get("final_score")
    score_str = f"{float(score):.1f}/10" if score is not None else "unscored"

    risks = (opp.get("risks") or [])[:3]
    risk_lines = "\n".join(f"- {r}" for r in risks) if risks else "- No explicit risks recorded -- derive them in /spec"

    phrases = (opp.get("exact_customer_phrases") or [])[:3]
    phrase_lines = "\n".join(f'- "{p}"' for p in phrases) if phrases else "- (no verbatim phrases captured yet)"

    return f"""# PROJECT.md -- {name}

> Generated by Daily Opportunity OS on {datetime.now().strftime('%Y-%m-%d')}
> from opportunity `{opp.get('id', '')}` (score {score_str}, lane {opp.get('portfolio_lane', '--')}).
> This is a SEED brief: validated signals are facts, everything else is hypothesis to test.

## What and Why

**Problem:** {_text_or(opp, 'problem_statement', 'TBD')}

**Target customer:** {_text_or(opp, 'target_customer', 'TBD')}

**Why now:** {_text_or(opp, 'why_now', 'TBD -- validate the timing thesis in /spec')}

**Customer voice:**
{phrase_lines}

## Market

- **Geography:** {geo}
- **Vertical:** {opp.get('vertical', 'TBD')}
- **TAM:** {opp.get('tam_display') or opp.get('tam') or 'not estimated'} (method: {opp.get('tam_method') or '--'}, confidence: {opp.get('tam_confidence') or '--'})
- **Direct competitors:** {_fmt_list(opp.get('direct_competitors'))}
- **Pricing benchmark:** {opp.get('pricing_benchmark') or 'none recorded'}
- **WTP anchor for {geo}:** {wtp_anchor}

## Go-to-Market

- **First revenue path:** {_text_or(opp, 'path_to_first_revenue', 'TBD -- define the first-revenue offer in /spec')}
- **Distribution channels:** {_fmt_list(opp.get('top_distribution_channels'), 4)}
- **CAC logic:** {opp.get('estimated_cac_logic') or 'TBD'}
- **First 10 customers:** {opp.get('first_10_customer_path') or 'TBD'}
- **Trust mechanism ({geo}):** {opp.get('trust_mechanism_latam') or 'TBD'}

## Constraints

- **Speed to MVP:** {opp.get('speed_to_mvp', '?')}/10 -- {opp.get('speed_to_mvp_reason') or 'aim for first working version in < 6 weeks'}
- **Capital:** {opp.get('capital_efficiency', '?')}/10 -- {opp.get('capital_efficiency_reason') or 'bootstrap budget, no inventory, no hires'}
- **Monetization:** {opp.get('monetization_model') or 'TBD -- decide in /spec'}

## Top Kill Risks

{risk_lines}

## Success Criteria (Phase 0)

- First proof point: {opp.get('first_proof_point_needed') or '3 paying customers in 30 days'}
- Revenue target: first paid customer via the path above, not via discounting
- Kill condition: if the pain cannot be confirmed with 5 customer conversations in 2 weeks, stop
"""


def build_kickoff_prompt(opp: dict) -> str:
    """The prompt to paste into a fresh Claude Code session."""
    name = opp.get("name", "this opportunity")
    slug = _slugify(name)
    geo = (opp.get("geography") or "global").lower()

    return f"""# Kickoff prompt -- {name}

Paste everything below this line into a fresh Claude Code session in your new
project folder (suggested: Projects/{slug}/), with PROJECT.md copied next to it.

---

Read PROJECT.md in this folder first -- it is the seed brief from my
opportunity-scouting pipeline. Treat validated signals as facts and
everything marked TBD/hypothesis as assumptions to challenge.

Then run /spec to define an MVP with these constraints:

1. **Goal:** reach the first revenue milestone via: {_text_or(opp, 'path_to_first_revenue', 'the first-revenue path in PROJECT.md')}
2. **Timebox:** MVP shippable in <= 6 weeks, solo founder + AI tooling
3. **Budget:** < $2K total before first revenue (APIs, hosting, tools)
4. **Market reality:** {geo} pricing -- {GEO_WTP_ANCHORS.get(geo, GEO_WTP_ANCHORS['global'])}
5. **Distribution-first:** the spec must include how the first 10 customers
   are reached ({_fmt_list(opp.get('top_distribution_channels'), 3)}),
   not just what gets built
6. **Scope discipline:** cut anything not needed to test the core pain:
   "{(opp.get('problem_statement') or '')[:140]}"

After /spec is confirmed, run /plan to break it into tasks.

Do NOT start coding until the spec answers: who pays, how much, reached how,
and what we learn if they say no.
"""


def write_kickoff_pack(opp_id: str, out_dir: Optional[str] = None) -> dict:
    """Write PROJECT.md + kickoff-prompt.md. Returns {files: [...]} or {error}."""
    opp = get_opportunity_by_id(opp_id)
    if opp is None:
        return {"error": f"Opportunity '{opp_id}' not found."}

    target = Path(out_dir) if out_dir else Path(get_project_root()) / "exports" / str(opp_id)[:60]
    target.mkdir(parents=True, exist_ok=True)

    files = []
    for filename, content in [
        ("PROJECT.md", build_project_md(opp)),
        ("kickoff-prompt.md", build_kickoff_prompt(opp)),
    ]:
        path = target / filename
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(content, encoding="utf-8")
        os.replace(tmp, path)
        files.append(str(path))

    return {"files": files}
